apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gamehub-back
spec:
  template:
    spec:
      containers:
        - image: gcr.io/gamehub-gcp/site:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"