name: GCP

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: GameHub-GCP
    env:
      REGISTRY: us-central1-docker.pkg.dev
      PROJECT_ID: gamehub-gcp
      REPOSITORY: cloud-run-source-deploy
      SERVICE: site
      REGION: us-central1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.PROJECT_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin ${{ env.REGISTRY }}

      - name: Build and Push to Artifact Registry
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --project ${{ env.PROJECT_ID }} \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --memory 512Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated \
            --no-cpu-throttling \
            --timeout=600s \
            --set-env-vars PORT=8080