name: GCP

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: GameHub-GCP
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/gamehub-gcp/cloud-run-source-deploy/site:latest
      REGION: us-central1
      SERVICE_NAME: site

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.PROJECT_CREDENTIALS }}
          project_id: gamehub-gcp
          export_default_credentials: true

      - name: Set project ID
        run: gcloud config set project gamehub-gcp

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Deploy Docker image
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} --project gamehub-gcp --image ${{ env.IMAGE_NAME }} --region ${{ env.REGION }} --memory 512Mi --min-instances 0 --max-instances 1 --platform managed --port 8080 --allow-unauthenticated --no-cpu-throttling --timeout=600s --set-env-vars PORT=8080 --startup-probe-path=/health --startup-probe-initial-delay=15 --startup-probe-period=5
