name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    environment: GameHub-GCP
    env:
      REGISTRY: us-east1-docker.pkg.dev
      IMAGE_NAME: ${{ secrets.PROJECT_ID }}/site-repo/gamehub
      REGION: us-east1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.PROJECT_CREDENTIALS }}

      - name: Auth Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGISTRY --quiet
          
      - name: Build Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy gamehub \
            --image $REGISTRY/$IMAGE_NAME:latest \
            --region $REGION \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --platform managed \
            --port 3000 \
            --allow-unauthenticated \
            --set-env-vars "$(node generate-env-vars.js)"