name: GCP

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: GameHub-GCP
    env:
      IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/site:latest
      REGION: us-central1
      SERVICE_NAME: site

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.PROJECT_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Set project ID
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Deploy Docker image
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} --project ${{ secrets.PROJECT_ID }} --image ${{ env.IMAGE_NAME }} --region ${{ env.REGION }} --memory 512Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated --no-cpu-throttling --timeout=600s
        env:
          PORT: 3000