name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - develop

env:
  REGION: us-central1          
  SERVICE_NAME: gamehub-back

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.PROJECT_CREDENTIALS }}

    - name: Configure Docker authentication
      run: |
        gcloud auth configure-docker gcr.io

    - name: Build and push Docker image
      run: |
        # Criar uma variável para a imagem com o PROJECT_ID corretamente interpolado
        IMAGE_NAME="gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        echo "Building image: $IMAGE_NAME"
        docker build -t "$IMAGE_NAME" .
        docker push "$IMAGE_NAME"
        # Salvar o nome da imagem para usar no próximo step
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.IMAGE_NAME }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}